
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izbnugizraqvrvlndzye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Ym51Z2l6cmFxdnJ2bG5kenllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTkzMTEsImV4cCI6MjA1MzEzNTMxMX0.fBWqxU5InNUXr7gCZvj6fTWNOHhJ2rqi6EbZXQm4ySQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create an untyped client for working with custom tables not in the generated types
export const supabaseUntyped = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
