
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nknrkkzegbrkqtutmafo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbnJra3plZ2Jya3F0dXRtYWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTQzNzUsImV4cCI6MjA1NzgzMDM3NX0.SggdJAWbi2cSM3gGP08NgCJLO2txiju9BivxU7Pznjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Typed client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Untyped client - useful for tables not yet in the generated types
export const supabaseUntyped = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
